---
version: "3"

services:
    hedron-1:
        container_name: hedron-1
        image: shivansh-hedron:1.0.0
        environment:
            PORT: "3001"
            HEDRON_REQUEST_TIMEOUT: "5"
            HEDRON_NODE_NAME: "HEDRON-1"
            HEDRON_NODE_PASSWORD: "shivansh"
            HEDRON_FELLOW_NODES: "[]"
            HEDRON_BASE_LOCATION: "/hedron-data/"
        ports:
            - "3001:3001"
            - "4001:4001"
    # hedron-2:
    #     container_name: hedron-2
    #     image: shivansh-hedron:1.0.0
    #     environment:
    #         PORT: "3002"
    #         HEDRON_REQUEST_TIMEOUT: "5"
    #         HEDRON_NODE_NAME: "HEDRON-2"
    #         HEDRON_NODE_PASSWORD: "shivansh"
    #         HEDRON_FELLOW_NODES: "[]"
    #         HEDRON_BASE_LOCATION: "/hedron-data/"
    #     ports:
    #         - "3002:3002"
    #         - "4002:4002"
    # hedron-3:
    #     container_name: hedron-3
    #     image: shivansh-hedron:1.0.0
    #     environment:
    #         PORT: "3003"
    #         HEDRON_REQUEST_TIMEOUT: "5"
    #         HEDRON_NODE_NAME: "HEDRON-3"
    #         HEDRON_NODE_PASSWORD: "shivansh"
    #         HEDRON_FELLOW_NODES: "[]"
    #         HEDRON_BASE_LOCATION: "/hedron-data/"
    #     ports:
    #         - "3003:3003"
    #         - "4003:4003"
